version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: jitome
    ports:
      - 3307:3306
    command: >
      mysqld
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_bin
  app:
    build: .
    restart: always
    ports:
      - 80:1234
    depends_on:
      - db
