version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jitome
    ports:
      - 3307:3306
    command: >
      mysqld
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_bin
