version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: jitome
    ports:
      - 3307:3306
    command: >
      mysqld
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_bin
    volumes:
      - ../jitome-kingdom-mysql:/var/lib/mysql
  app:
    image: 941528793676.dkr.ecr.ap-northeast-1.amazonaws.com/jitome-kingdom-api/prod:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - 80:1234
    depends_on:
      - db
  app_janken_task:
    image: 941528793676.dkr.ecr.ap-northeast-1.amazonaws.com/jitome-kingdom-api/prod:latest
    restart: always
    environment:
      EXECUTION_TASK: janken
    env_file:
      - ./.env
    ports:
      - 80:1234
    depends_on:
      - db
